### ISSUE TITLE
Show link from lane to parent

### ISSUE THREAD

**Issue by skomputer** [NYPL-Simplified/opds-browser#34]

**Comment by aslagle** [comment]
This is blocked by https://github.com/NYPL-Simplified/circulation/issues/69.

Our up links are broken, and the OPDS test catalog doesn't seem to have up links. I'm not sure if they're actually part of OPDS.

**Comment by HadrienGardeur** [comment]
@aslagle do you mean something like link@rel="up"?

**Comment by HadrienGardeur** [comment]
OK, just checked the other issue that you reference and that's the case.

There's no such thing in OPDS officially, and it's a little bit tricky.

You can actually reach a specific OPDS feed or entry in different ways, which means that "up" would mean something different than the "back" action from your browser.

If you're familiar with Android, this is similar to the difference between the back action in the Action Bar of your app (which goes back in the hierarchy of the app) vs the back action from Android itself (which pretty much behaves like back in a browser). 

This can get very confusing from a UX perspective, any specific reason why you'd need "up"?

**Comment by aslagle** [comment]
We'd like the pages to have permanent links that can be shared and bookmarked, so we may not have the history of where the user came from. It seems like a lot to put in the url. It would be nice if all the information on the page could come from the current feed. The back button does work, if you're trying to reach the feed you came from.

I wasn't sure using the up link was correct, I agree it could be confusing. @winniequinn what do the iOS and android apps do?

**Comment by HadrienGardeur** [comment]
Aside from moving "up" in the hierarchy of the catalog, you can also link back at any time to the homepage (link@rel="start"), that part is supported by the specification.
