### ISSUE TITLE
Escape search terms

### ISSUE THREAD

**Issue by HadrienGardeur** [NYPL-Simplified/opds-browser#61]
See: https://sleepy-peak-65428.herokuapp.com/?url=http://bibliomedia.cantookstation.eu/catalog/search.atom?q=Ind%C3%A9sirable

**Comment by aslagle** [comment]
That url still won't work, but now this will: https://sleepy-peak-65428.herokuapp.com/?url=http%3A%2F%2Fbibliomedia.cantookstation.eu%2Fcatalog%2Fsearch.atom%3Fq%3DInd%25C3%25A9sirable

And typing into the search box will work correctly.
