### ISSUE TITLE
Show description instead of summary when both available

### ISSUE THREAD

**Issue by HadrienGardeur** [NYPL-Simplified/opds-browser#70]
When both description and summary are available, the OPDS client should display the description. This is testable with the OPDS Test Catalog, the fourth publication is meant to test it: https://sleepy-peak-65428.herokuapp.com/?url=http%3A%2F%2Ffeedbooks.github.io%2Fopds-test-catalog%2Fcatalog%2Facquisition%2Fmain.xml

**Comment by aslagle** [comment]
@HadrienGardeur: do you think the parser should keep both of them?

I have the parser setting summary to atom:summary if it's present, and atom:content if that's present but atom:summary isn't. 

I can switch those, or have the parser extract both and the browser decide what to display. Would you ever want to show both?

**Comment by HadrienGardeur** [comment]
I don't think you're likely to want both, but there's one case that I can think about: if one is using plain text and the other HTML, a client might decide that it either wants one or the other.

Expected behavior for any OPDS client though, is to display content instead of summary if available.

**Comment by aslagle** [comment]
Okay, I'm switching them in the parser for now. We can change it later to save both if we need it.

**Comment by aslagle** [comment]
This is done, will be fixed next time we deploy.
