### ISSUE TITLE
Book details should be scrollable if the summary is long

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/opds-browser#74]
Example book with a long summary 

http://circulation.librarysimplified.org/works/Overdrive/135d0478-1ab9-4cc1-a1aa-2aa616b1218c

**Comment by HadrienGardeur** [comment]
You want them to be scrollable for another reason: links.

Right now, the client doesn't display entry level links, but these can be used to link to other books from the same author, rest of the books in a specific series etc.

Such links can be displayed in a few different ways, the most common ones being: just displaying the text or actually fetching the feed and displaying that as a block/lane.
