### ISSUE TITLE
Choose Flux implementation

### ISSUE THREAD

**Issue by skomputer** [NYPL-Simplified/opds-browser#8]
React applications typically employ a [Flux architecture](https://facebook.github.io/flux/docs/overview.html) to organize data flow. There are a number of existing Flux implementations, including [Facebook Flux](https://facebook.github.io/flux/), [Reflux](https://github.com/reflux/refluxjs), [Alt](http://alt.js.org/), and [Redux](http://redux.js.org/). Choose one.

**Comment by skomputer** [comment]
Decision: Redux, because immutable state is nice and I've used Redux a bunch already.

**Comment by gwendolen** [comment]
\*signs off on Redux\*
